name: Release packed CLI privately

on:
  push:
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.PKG_RELEASE_TOKEN  }}

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: npm ci
      - name: Build tarball
        # does not bundle node
        run: npx oclif-dev pack --targets=
      - name: Determine version
        id: version
        shell: bash
        run: |
          VERSION=$(cat package.json | jq --raw-output .version)
          echo "::set-output name=tag::${VERSION}"
      - name: Create release if not exists
        # ignore failures if the release already exists
        run: gh release create --repo netlify/cli-private-packs v${{ steps.version.outputs.tag }} || true
      - name: Upload release asset
        run: |
          gh release upload --repo netlify/cli-private-packs v${{ steps.version.outputs.tag }} \
          'dist/netlify-v${{ steps.version.outputs.tag }}/netlify-v${{ steps.version.outputs.tag }}.tar.gz#netlify-cli.tar.gz'
