name: Publish Release Asset

on:
  push:
#    tags:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2
      - name: Install deps
        run: npm ci
      - name: Build tarball
        # does not bundle node
        run: npx oclif-dev pack --targets=
      - name: Determine version
        id: version
        shell: bash
        run: |
          VERSION=$(cat package.json | jq --raw .version)
          echo "::set-output name=tag::${VERSION}"
      - name: Create release if not exists
        # ignore failures if the release already exists
        run: gh release create v${{ steps.version.tag }}.ci-test || true
      - name: Upload release asset
        run: |
          gh release upload --clobber v${{ steps.version.tag }}.ci-test \
          dist/netlify-v${{ steps.version.tag }}/netlify-v${{ steps.version.tag }}.tar.gz
